// Clean mock dataset for UI/testing: window.tables is an array of table metadata objects.
// Schema: { name, schemaname, description, columns: [ { id, name, size, format, mandatory, FK, Notes, C900 } ] }
window.tables = [
	{
		name: 'users',
		schemaname: 'public.users',
		description: 'Application users and their profile metadata',
		columns: [
			{
				id: 'id',
				name: 'id',
				size: 'uuid',
				format: 'string',
				mandatory: 'yes',
				FK: '',
				Notes: 'Primary key',
				C900: 'PK',
			},
			{
				id: 'username',
				name: 'username',
				size: '50',
				format: 'string',
				mandatory: 'yes',
				FK: '',
				Notes: 'Login name, unique',
				C900: 'IDX',
			},
			{
				id: 'email',
				name: 'email',
				size: '100',
				format: 'email',
				mandatory: 'yes',
				FK: '',
				Notes: 'Contact email',
				C900: '',
			},
			{
				id: 'display_name',
				name: 'display_name',
				size: '100',
				format: 'string',
				mandatory: 'no',
				FK: '',
				Notes: 'Shown on profiles',
				C900: '',
			},
			{
				id: 'created_at',
				name: 'created_at',
				size: 'timestamp',
				format: 'datetime',
				mandatory: 'yes',
				FK: '',
				Notes: 'Account creation time',
				C900: '',
			},
		],
	},
	{
		name: 'posts',
		schemaname: 'public.posts',
		description: 'User-generated posts and their metadata',
		columns: [
			{
				id: 'id',
				name: 'id',
				size: 'bigint',
				format: 'integer',
				mandatory: 'yes',
				FK: '',
				Notes: 'Primary key',
				C900: 'PK',
			},
			{
				id: 'author_id',
				name: 'author_id',
				size: 'uuid',
				format: 'string',
				mandatory: 'yes',
				FK: 'users.id',
				Notes: 'FK to users table',
				C900: 'FK',
			},
			{
				id: 'title',
				name: 'title',
				size: '200',
				format: 'string',
				mandatory: 'yes',
				FK: '',
				Notes: 'Post title',
				C900: '',
			},
			{
				id: 'body',
				name: 'body',
				size: 'unbounded',
				format: 'text',
				mandatory: 'no',
				FK: '',
				Notes: 'Main content',
				C900: '',
			},
			{
				id: 'published',
				name: 'published',
				size: 'boolean',
				format: 'bool',
				mandatory: 'yes',
				FK: '',
				Notes: 'Published flag',
				C900: '',
			},
			{
				id: 'published_at',
				name: 'published_at',
				size: 'timestamp',
				format: 'datetime',
				mandatory: 'no',
				FK: '',
				Notes: 'When published',
				C900: '',
			},
		],
	},
	{
		name: 'comments',
		schemaname: 'public.comments',
		description: 'Comments left on posts',
		columns: [
			{
				id: 'id',
				name: 'id',
				size: 'bigint',
				format: 'integer',
				mandatory: 'yes',
				FK: '',
				Notes: 'Primary key',
				C900: 'PK',
			},
			{
				id: 'post_id',
				name: 'post_id',
				size: 'bigint',
				format: 'integer',
				mandatory: 'yes',
				FK: 'posts.id',
				Notes: 'FK to posts',
				C900: 'FK',
			},
			{
				id: 'author_id',
				name: 'author_id',
				size: 'uuid',
				format: 'string',
				mandatory: 'no',
				FK: 'users.id',
				Notes: 'Optional author',
				C900: '',
			},
			{
				id: 'content',
				name: 'content',
				size: 'unbounded',
				format: 'text',
				mandatory: 'yes',
				FK: '',
				Notes: 'Comment body',
				C900: '',
			},
			{
				id: 'created_at',
				name: 'created_at',
				size: 'timestamp',
				format: 'datetime',
				mandatory: 'yes',
				FK: '',
				Notes: 'Creation time',
				C900: '',
			},
		],
	},
	{
		name: 'tags',
		schemaname: 'public.tags',
		description: 'Simple tags for posts',
		columns: [
			{
				id: 'id',
				name: 'id',
				size: 'int',
				format: 'integer',
				mandatory: 'yes',
				FK: '',
				Notes: 'Primary key',
				C900: 'PK',
			},
			{
				id: 'tag',
				name: 'tag',
				size: '50',
				format: 'string',
				mandatory: 'yes',
				FK: '',
				Notes: 'Tag text',
				C900: 'IDX',
			},
		],
	},
	{
		name: 'post_tags',
		schemaname: 'public.post_tags',
		description: 'Join table between posts and tags',
		columns: [
			{
				id: 'post_id',
				name: 'post_id',
				size: 'bigint',
				format: 'integer',
				mandatory: 'yes',
				FK: 'posts.id',
				Notes: 'FK to posts',
				C900: 'FK',
			},
			{
				id: 'tag_id',
				name: 'tag_id',
				size: 'int',
				format: 'integer',
				mandatory: 'yes',
				FK: 'tags.id',
				Notes: 'FK to tags',
				C900: 'FK',
			},
		],
	},
	{
		name: 'post_tags',
		schemaname: 'public.post_tags',
		description: 'Join table between posts and tags',
		columns: [
			{
				id: 'post_id',
				name: 'post_id',
				size: 'bigint',
				format: 'integer',
				mandatory: 'yes',
				FK: 'posts.id',
				Notes: 'FK to posts',
				C900: 'FK',
			},
			{
				id: 'tag_id',
				name: 'tag_id',
				size: 'int',
				format: 'integer',
				mandatory: 'yes',
				FK: 'tags.id',
				Notes: 'FK to tags',
				C900: 'FK',
			},
		],
	},
	{
		name: 'post_tags',
		schemaname: 'public.post_tags',
		description: 'Join table between posts and tags',
		columns: [
			{
				id: 'post_id',
				name: 'post_id',
				size: 'bigint',
				format: 'integer',
				mandatory: 'yes',
				FK: 'posts.id',
				Notes: 'FK to posts',
				C900: 'FK',
			},
			{
				id: 'tag_id',
				name: 'tag_id',
				size: 'int',
				format: 'integer',
				mandatory: 'yes',
				FK: 'tags.id',
				Notes: 'FK to tags',
				C900: 'FK',
			},
		],
	},
	{
		name: 'post_tags',
		schemaname: 'public.post_tags',
		description: 'Join table between posts and tags',
		columns: [
			{
				id: 'post_id',
				name: 'post_id',
				size: 'bigint',
				format: 'integer',
				mandatory: 'yes',
				FK: 'posts.id',
				Notes: 'FK to posts',
				C900: 'FK',
			},
			{
				id: 'tag_id',
				name: 'tag_id',
				size: 'int',
				format: 'integer',
				mandatory: 'yes',
				FK: 'tags.id',
				Notes: 'FK to tags',
				C900: 'FK',
			},
		],
	},
	{
		name: 'post_tags',
		schemaname: 'public.post_tags',
		description: 'Join table between posts and tags',
		columns: [
			{
				id: 'post_id',
				name: 'post_id',
				size: 'bigint',
				format: 'integer',
				mandatory: 'yes',
				FK: 'posts.id',
				Notes: 'FK to posts',
				C900: 'FK',
			},
			{
				id: 'tag_id',
				name: 'tag_id',
				size: 'int',
				format: 'integer',
				mandatory: 'yes',
				FK: 'tags.id',
				Notes: 'FK to tags',
				C900: 'FK',
			},
		],
	},
	{
		name: 'post_tags',
		schemaname: 'public.post_tags',
		description: 'Join table between posts and tags',
		columns: [
			{
				id: 'post_id',
				name: 'post_id',
				size: 'bigint',
				format: 'integer',
				mandatory: 'yes',
				FK: 'posts.id',
				Notes: 'FK to posts',
				C900: 'FK',
			},
			{
				id: 'tag_id',
				name: 'tag_id',
				size: 'int',
				format: 'integer',
				mandatory: 'yes',
				FK: 'tags.id',
				Notes: 'FK to tags',
				C900: 'FK',
			},
		],
	},
	{
		name: 'post_tags',
		schemaname: 'public.post_tags',
		description: 'Join table between posts and tags',
		columns: [
			{
				id: 'post_id',
				name: 'post_id',
				size: 'bigint',
				format: 'integer',
				mandatory: 'yes',
				FK: 'posts.id',
				Notes: 'FK to posts',
				C900: 'FK',
			},
			{
				id: 'tag_id',
				name: 'tag_id',
				size: 'int',
				format: 'integer',
				mandatory: 'yes',
				FK: 'tags.id',
				Notes: 'FK to tags',
				C900: 'FK',
			},
		],
	},
	{
		name: 'post_tags',
		schemaname: 'public.post_tags',
		description: 'Join table between posts and tags',
		columns: [
			{
				id: 'post_id',
				name: 'post_id',
				size: 'bigint',
				format: 'integer',
				mandatory: 'yes',
				FK: 'posts.id',
				Notes: 'FK to posts',
				C900: 'FK',
			},
			{
				id: 'tag_id',
				name: 'tag_id',
				size: 'int',
				format: 'integer',
				mandatory: 'yes',
				FK: 'tags.id',
				Notes: 'FK to tags',
				C900: 'FK',
			},
		],
	},
	{
		name: 'post_tags',
		schemaname: 'public.post_tags',
		description: 'Join table between posts and tags',
		columns: [
			{
				id: 'post_id',
				name: 'post_id',
				size: 'bigint',
				format: 'integer',
				mandatory: 'yes',
				FK: 'posts.id',
				Notes: 'FK to posts',
				C900: 'FK',
			},
			{
				id: 'tag_id',
				name: 'tag_id',
				size: 'int',
				format: 'integer',
				mandatory: 'yes',
				FK: 'tags.id',
				Notes: 'FK to tags',
				C900: 'FK',
			},
		],
	},
	{
		name: 'post_tags',
		schemaname: 'public.post_tags',
		description: 'Join table between posts and tags',
		columns: [
			{
				id: 'post_id',
				name: 'post_id',
				size: 'bigint',
				format: 'integer',
				mandatory: 'yes',
				FK: 'posts.id',
				Notes: 'FK to posts',
				C900: 'FK',
			},
			{
				id: 'tag_id',
				name: 'tag_id',
				size: 'int',
				format: 'integer',
				mandatory: 'yes',
				FK: 'tags.id',
				Notes: 'FK to tags',
				C900: 'FK',
			},
		],
	},
	{
		name: 'post_tags',
		schemaname: 'public.post_tags',
		description: 'Join table between posts and tags',
		columns: [
			{
				id: 'post_id',
				name: 'post_id',
				size: 'bigint',
				format: 'integer',
				mandatory: 'yes',
				FK: 'posts.id',
				Notes: 'FK to posts',
				C900: 'FK',
			},
			{
				id: 'tag_id',
				name: 'tag_id',
				size: 'int',
				format: 'integer',
				mandatory: 'yes',
				FK: 'tags.id',
				Notes: 'FK to tags',
				C900: 'FK',
			},
		],
	},
	{
		name: 'post_tags',
		schemaname: 'public.post_tags',
		description: 'Join table between posts and tags',
		columns: [
			{
				id: 'post_id',
				name: 'post_id',
				size: 'bigint',
				format: 'integer',
				mandatory: 'yes',
				FK: 'posts.id',
				Notes: 'FK to posts',
				C900: 'FK',
			},
			{
				id: 'tag_id',
				name: 'tag_id',
				size: 'int',
				format: 'integer',
				mandatory: 'yes',
				FK: 'tags.id',
				Notes: 'FK to tags',
				C900: 'FK',
			},
		],
	},
	{
		name: 'post_tags',
		schemaname: 'public.post_tags',
		description: 'Join table between posts and tags',
		columns: [
			{
				id: 'post_id',
				name: 'post_id',
				size: 'bigint',
				format: 'integer',
				mandatory: 'yes',
				FK: 'posts.id',
				Notes: 'FK to posts',
				C900: 'FK',
			},
			{
				id: 'tag_id',
				name: 'tag_id',
				size: 'int',
				format: 'integer',
				mandatory: 'yes',
				FK: 'tags.id',
				Notes: 'FK to tags',
				C900: 'FK',
			},
		],
	},
	{
		name: 'post_tags',
		schemaname: 'public.post_tags',
		description: 'Join table between posts and tags',
		columns: [
			{
				id: 'post_id',
				name: 'post_id',
				size: 'bigint',
				format: 'integer',
				mandatory: 'yes',
				FK: 'posts.id',
				Notes: 'FK to posts',
				C900: 'FK',
			},
			{
				id: 'tag_id',
				name: 'tag_id',
				size: 'int',
				format: 'integer',
				mandatory: 'yes',
				FK: 'tags.id',
				Notes: 'FK to tags',
				C900: 'FK',
			},
		],
	},
];
